### ISSUE TITLE
该项目ViewModel 间接通过BaseUIController 持有View ，这样不会导致内存泄漏吗？

### ISSUE THREAD

**Issue by woyoudianhuai** [afkT/DevComponent#3]

**Comment by afkT** [comment]
不会导致内存泄露，因为持有的 `DevBaseContentAssist` 该类是在`BaseActivity`、`BaseFragment` 中 `findViewById` 自定义的 Base XML View，并且在 `BaseUIController` 进行的是 `addView`、`removeView`、`goneView`、`visibleView` 并不会直接获取 View 并进行声明持有，例如通过动态添加 `StatusBar`、`TitleBar` 等骨架 View 到 Base XML View 里面

**Comment by woyoudianhuai** [comment]
目前来看，该项目是没有处理好内存泄漏问题，实际上LeackyCannary 还是检测出了不少内存泄漏。非标准的mvvm

**Comment by woyoudianhuai** [comment]
![Uploading 1726039840750.jpg…]()

**Comment by woyoudianhuai** [comment]
![1726040518947](https://github.com/user-attachments/assets/5f1f4ad4-884b-406e-9fe0-331b7ebc9494)

**Comment by woyoudianhuai** [comment]
viewModel 持有View的话，风险还是很大的，需要手动管理，必须在UI层销毁时及时的清除View
